name: 11pm

on: 
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'


jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Bot
      run: Invoke-WebRequest https://github.com/TheGimireJr/ContentIsPower-ForGigmire-Baba/blob/main/Final-Script.zip?raw=true -OutFile Final-Script.zip
    - name: Extract Bot
      run: Expand-Archive Final-Script.zip
    - name: Installing requirements
      shell: pwsh
      run: pip install -r .\Final-Script\Final-Script\requirements.txt
    - name: Running-Bot
      shell: pwsh
      run: python .\Final-Script\Final-Script\main.py